### ISSUE TITLE
lambda error

### ISSUE THREAD

**Issue by b3yond** [sidtechnical/hakuna-metadata-1#2]
Hi again, 

I followed your instructions from https://github.com/sidtechnical/hakuna-metadata-1/issues/1 and it worked, they renamed the module, as you say. Thanks for making the effort of debugging :)

shortly after though, another error pops up; as it seems they changed more than just the module name.

I'd understand it completely, if you didn't want to align to the new pandas version and rewrite everything^^ maybe you can just give name the version of pandas with which it works?

```
$ python tool.py 
################################################################################################
Please be patient. This might take a while. 
When the tool completes running, it automatically opens a browser tab and displays the visuals.

Unless the program stops with errors, ignore the warnings/messages if any.

If you want to interrupt the program execution, please press CTRL+C.
################################################################################################
No handlers could be found for logger "tldextract"
Traceback (most recent call last):
  File "tool.py", line 480, in <module>
    Unique_URLs_df['Unique_URL_Count'] = Unique_URLs_df.apply(lambda row: Count_Unique_URLs(row['Unique_URLs']), axis=1)                                                            
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2355, in apply                                                                                          
    mapped = lib.map_infer(values, f, convert=convert_dtype)                                                                                                                        
  File "pandas/_libs/src/inference.pyx", line 1569, in pandas._libs.lib.map_infer (pandas/_libs/lib.c:66440)                                                                        
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2342, in <lambda>                                                                                       
    f = lambda x: func(x, *args, **kwds)                                                                                                                                            
TypeError: <lambda>() got an unexpected keyword argument 'axis'
```

**Comment by donkeyDau** [comment]
Jup. Running into the same issue with panda 0.20.1

**Comment by sidtechnical** [comment]
@b3yond @donkeyDau  Ooopsie! I will update it soon (After Monday)

It is working fine in pandas 0.18.1, Easiest way that I will update the same in requirements.
